create: stat_svc
ValeryyBesch/java-explore-with-me pull request #1
Opened 2024-05-18 19:13 UTC by ValeryyBesch

2024-05-19 19:46 UTC, z8q requested changes

2024-05-19 19:46 UTC, z8q commented on docker-compose.yml
> +    - STAT_PASSWORD_DB=123
Лучше следовать стандартному неймингу, в соответствии с application.properties

в compose
```
environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://state_server-db:5432/stat_db
      - SPRING_DATASOURCE_USERNAME=asd
      - SPRING_DATASOURCE_PASSWORD=123
```
в  application.properties
```
spring.datasource.url=jdbc:postgresql://stats_service-db:5432/stat_db
spring.datasource.username=asd
spring.datasource.password=123
```

2024-05-19 19:46 UTC, z8q commented on docker-compose.yml
> +    container_name: postgres-main-db
Имена контейнеров можно привести к одному виду (разделители межу словами).
Сейчас так
```
container_name: stat_server
container_name: stat_server-db
container_name: ewm-service
container_name: postgres-main-db
```

2024-05-19 19:46 UTC, z8q commented on docker-compose.yml
> +      - "9091:9091"
91-й для чего?

2024-05-19 19:46 UTC, z8q commented on ewm-stat-service/stat_client/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
тоже можно, как и в stat_server, использовать
```
<version>${project.version}</version>
```

2024-05-19 19:46 UTC, z8q commented on ewm-stat-service/stat_server/src/main/java/ru/practicum/model/Stat.java
> +@EqualsAndHashCode
В сущностях хибернейта не рекомендуется использовать equals и hashcode 
и `@Data` –  он содержит в себе equals и hashcode 
лонгриды [тут](https://jpa-buddy.com/blog/hopefully-the-final-article-about-equals-and-hashcode-for-jpa-entities-with-db-generated-ids/) и [тут](https://vladmihalcea.com/hibernate-facts-equals-and-hashcode/)

2024-05-19 19:46 UTC, z8q commented on ewm-stat-service/stat_server/src/main/java/ru/practicum/repository/StatServiceRepository.java
> +            "where stat.timestamp between ?1 and ?2 and stat.uri in ?3 " +
Можно использовать [@Param](https://vladmihalcea.com/hibernate-facts-equals-and-hashcode/) вместо ?1, ?2, ?3

2024-05-22 13:09 UTC, ValeryyBesch commented on docker-compose.yml
> +    - STAT_PASSWORD_DB=123
хм, странно, при изменении этого замечания не получается пройти тест, надеюсь это не критичное замечание, оставил так как есть

2024-05-22 20:19 UTC, z8q approved these changes

2024-05-22 20:19 UTC, z8q commented on docker-compose.yml
> +    - STAT_PASSWORD_DB=123
сорри, в первом комментарии не обратил внимание на такой момент.
Название сервиса с базой в docker-compose – stats_service-db
мы пытались определить переменную таким образом
```
- SPRING_DATASOURCE_URL=jdbc:postgresql://state_server-db:5432/stat_db
```
где **state_server**-db не равно **stats_service**-db (название сервиса с базой отличается)

Когда мы задаем переменную SPRING_DATASOURCE_URL, мы переопределяем проперти из application.properties – spring.datasource.url
Она сейчас задана таким образом
```
spring.datasource.url=jdbc:postgresql://stats_service-db:5432/stat_db
```
мы видим, что в application.properties сервис указан верно – stats_service-db

это объясняет, почему с переменной STAT_URL_DB все работает
```
- STAT_URL_DB=jdbc:postgresql://state_server-db:5432/stat_db
```
Она не переопределяет настройку из application.properties, поэтому подключение происходит корректно.

Для проверки можно сделать таким образом.
В application.properties задать проперти таким образом:
```
spring.datasource.url=jdbc:postgresql://localhost:5432/stat_db
spring.datasource.username=root
spring.datasource.password=root
```
для сервиса stats-server в компоуз будет так:
```
environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats_service-db:5432/stat_db
      - SPRING_DATASOURCE_USERNAME=asd
      - SPRING_DATASOURCE_PASSWORD=123
```

должно сработать

2024-05-22 20:19 UTC, z8q commented on docker-compose.yml
> +    - STAT_PASSWORD_DB=123
настройки stats_service-db в компоуз останутся без изменений

2024-05-22 20:47 UTC, merged