create: main_svc
ValeryyBesch/java-explore-with-me pull request #2
Opened 2024-05-23 06:26 UTC by ValeryyBesch

2024-05-23 18:27 UTC, z8q requested changes

2024-05-23 18:27 UTC, z8q commented on docker-compose.yml
>       - "8080:8080"
Надо же попробовать применить то, что обсуждали в прошлой домашке по docker-compose)

2024-05-23 18:27 UTC, z8q commented on ewm-main-service/src/main/java/ru/practicum/main/event/repository/EventMainServiceRepository.java
> +        "AND (?6 = false OR ((?6 = true AND e.participantLimit > (SELECT count(*) FROM Request AS r WHERE e.id = r.event.id))) " +
Вложенных селектов стоит избегать.
Можно попробовать переписать без вложенного запроса

2024-05-23 18:27 UTC, z8q commented on ewm-main-service/src/main/java/ru/practicum/main/event/repository/EventMainServiceRepository.java
> +        "WHERE ((?1 IS null) OR ((lower(e.annotation) LIKE concat('%', lower(?1), '%')) OR (lower(e.description) LIKE concat('%', lower(?1), '%')))) " +
Вместо ?1 ?2 ?3 можно применить аннотацию Param. Описана [тут](https://www.baeldung.com/spring-data-jpa-query#1-jpql-4)

2024-05-23 18:27 UTC, z8q commented on ewm-main-service/src/main/java/ru/practicum/main/event/service/EventPrivateServiceImpl.java
> +        requestShort.getRequestIds().forEach(requestId -> {
В цикле присутствуют запросы в базу. По возможности, стоит сокращать количество запросов в базу. Например  – передавать id сразу списком

2024-05-23 18:27 UTC, z8q commented on ewm-main-service/src/main/resources/application.properties
>  spring.datasource.url=${MAIN_DB}
Можно и так), тогда для stat-server проперти нужно тоже применить

2024-05-24 13:00 UTC, ValeryyBesch commented on ewm-main-service/src/main/java/ru/practicum/main/event/repository/EventMainServiceRepository.java
> +        "WHERE ((?1 IS null) OR ((lower(e.annotation) LIKE concat('%', lower(?1), '%')) OR (lower(e.description) LIKE concat('%', lower(?1), '%')))) " +
странно, вроде делал как раньше, но не проходит проверку, надеюсь это не критично

2024-05-24 18:25 UTC, z8q approved these changes

2024-05-24 18:57 UTC, ValeryyBesch commented on ewm-main-service/src/main/java/ru/practicum/main/event/repository/EventMainServiceRepository.java
> +        "AND (?6 = false OR ((?6 = true AND e.participantLimit > (SELECT count(*) FROM Request AS r WHERE e.id = r.event.id))) " +
не знаю почему, но не получаеться сделать без вложенного цикла

2024-05-26 11:26 UTC, merged